### ISSUE TITLE
Can't add a SourceForge project discussion feed

### ISSUE THREAD

**Issue by taa1** [Xyrio/RSSOwl#1]
Hi,

I'm running 2.4.0 beta 32bit on Windows 10. I'm brand new to RSSOwl. I'm trying to add a new feed by going to File -> New -> Feed and typing in a direct link:

https://sourceforge.net/p/gnuwin32/discussion/feed.rss

I've tried checking and unchecking "Use the title of the feed as name" but get the same results either way: 
1. Clicking on NEXT gives me "Unable to load the title from the feed" so I'm prompted for one.
2. I type in GNUWin32 and click FINISH.
3. I see GNUWin32 appear in my Feeds list but its icon has a red checkmark in the lower right corner.

What am I doing wrong?

Java version info:

~~~
C:\temp>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode)
~~~

**Comment by Xyrio** [comment]
right click on the feed go properties then status. what does it say for status?
if it saies at the end "handshade_failure" you need to install JCE. from java 9 onward this is not necessary anymore. 

see https://sourceforge.net/p/rssowl/discussion/296910/thread/6dc4a203/

**Comment by taa1** [comment]
Hi,

I installed JCE but I'm still getting handshake_failure. I posted details [at the SourceForge link](https://sourceforge.net/p/rssowl/discussion/296910/thread/6dc4a203/#a510) but I guess that thread is not actively monitored so I'll re-post the info here.

RSSOwl version 2.4.0.201712100124 on Windows 10.

~~~
C:\temp>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode)

C:\temp>
~~~

I installed the java 8 files to

~~~
C:\Program Files (x86)\Java\jre1.8.0_151\lib\security\policy\unlimited
~~~

restarted RSSOwl, but it still doesn't access the feed at https://sourceforge.net/p/gnuwin32/discussion/feed.rss.

~~~
Error loading 'GNUWin32'
Problem: Received fatal alert: handshake_failure
Link: https://sourceforge.net/p/gnuwin32/discussion/feed.rss
~~~

I'm attaching the results of going to: https://www.ssllabs.com/ssltest/

[SSL Server Test_ sourceforge.pdf](https://github.com/Xyrio/RSSOwl/files/1690233/SSL.Server.Test_.sourceforge.pdf)

**Comment by Xyrio** [comment]
it works for me. the diffeence i can see is that i put the jce files into: 
`C:\Program Files (x86)\Java\jre1.8.0_151\lib\security`

**Comment by taa1** [comment]
That took care of it -- thank you!
